### ISSUE TITLE
issues adding multiple dell servers

### ISSUE THREAD

**Issue by smitch35** [Breina/idrac_power_monitor#11] opened 2024-02-20 20:22 UTC
I recently updated to the newest version and now if I add all 4 of my servers I only get some reporting info from a couple and never all four and it will randomly change which ones it polls from.

Is this something you've run across or is there a best practice for adding multiple dell servers to this integration?

Thanks,

**Comment by Breina** [comment] 2024-02-21 10:40
Can you please enable debug logging and check how often you see `Refreshing sensors` in the logs? You should see it once per server per `interval` that you configured (5 minutes by default). If values are the same, I don't refresh the entity.

**Comment by Arhkos** [comment] 2024-02-22 11:36
Same issue for me.

2 x R630 and reports are mixed

Difference in entity reported
![image](https://github.com/Breina/idrac_power_monitor/assets/87340721/9a312d65-0685-48f5-be9d-b2b8cb1d24a8)

In one entity all sensor are doubled because its report sensor of serveur 1 and 2
![image](https://github.com/Breina/idrac_power_monitor/assets/87340721/cc6a6f94-6bf6-4227-b17c-7aa53ceb7dec)

Only one entity is show in my integration pannel 
![image](https://github.com/Breina/idrac_power_monitor/assets/87340721/2018fda9-14d2-4b03-8c42-0c6086abf115)

**Comment by smitch35** [comment] 2024-02-22 12:42
I'm guessing since it sees each device as 'the same device' that's what's causing the issue
![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/8634fc97-0557-479a-8569-1f493d4ea80f)

**Comment by Breina** [comment] 2024-02-22 14:16
Good report! I see what's going on, let me fix that for you! :)

**Comment by Breina** [comment] 2024-02-22 14:45
Can you please do this?

`curl --location --request GET 'https://HOST/redfish/v1/Chassis/System.Embedded.1' \
--header 'Authorization: Basic BASIC_TOKEN'`

Replacing `HOST` and `BASIC_TOKEN`. Basic token should be [base64 encoded ](https://www.base64encode.org/) `yourusername:yourpassword`.

To differentiate devices, the model and serial are used for uniqueness. I am guessing that there's a problem parsing the `SerialNumber` from the response of the above REST call.

---

The last screenshot shows a different issue, I fixed that (not yet released).

**Comment by smitch35** [comment] 2024-02-22 15:06
I may be doing something wrong .
I'm getting this
[image: image.png]

and this:
[image: image.png]

**Comment by Arhkos** [comment] 2024-02-22 15:20
curl didnt work cause insecure certificat (its a selfsigned from the idrac) but i can access to https://HOST/redfish/v1/Chassis/System.Embedded.1  with my webbrowser. Did the result of this helping ? If yes I can paste it

**Comment by smitch35** [comment] 2024-02-22 15:26
Yes I can get the output in a browser and it does see the serial number it
seems
[image: image.png]

[image: image.png]

**Comment by Arhkos** [comment] 2024-02-22 15:28
@smitch35 image from email didnt work :D

**Comment by smitch35** [comment] 2024-02-22 15:30
Sorry!

![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/7b6bb4d3-25a4-4ed5-b80a-f06f6e38c43c)

![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/b7e1a2e6-bbbd-4951-825a-e158d48243df)

**Comment by Breina** [comment] 2024-02-22 16:58
Ok thanks for the data guys!

**Comment by Breina** [comment] 2024-02-22 17:52
Alright I'm not exactly sure, but can you please test this release?

https://github.com/Breina/idrac_power_monitor/releases/tag/v1.2.2alpha

You may need to completely remove all config entries and entities first.

**Comment by smitch35** [comment] 2024-02-22 18:20
So it looks better but there's some oddities

![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/d0556db5-d421-4909-9423-cbb848f297b5)
As you can see its still not grabbing everything after the first server is added

![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/2eeeef3c-8044-4773-ac32-da1d2ddc7fe9)

power usage is almost working.  The power buttons worked for each device but only server 1 has actually updated it's power usage that it's on giving it a higher wattage.

Not sure if i did this right I just pulled downe the tar in the custom_compoenents section, untarred it, named idrac_power to idrac_power_backup and the alpha to idrac_power and restarted HA

**Comment by Breina** [comment] 2024-02-22 18:23
Just to rule out some stuff, could you please remove the integration completely, restart, then remove all of its (now disabled) entities, then add the integration once again. I'm still not sure why it's doing it like this.

**Comment by smitch35** [comment] 2024-02-22 18:41
This looks like it may be working
![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/fa14ed22-795e-4beb-929c-c57fd2b1a558)

It's slowly but surely grabbing everything 
![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/2863db14-49ef-4055-b287-7e331dd37512)

**Comment by smitch35** [comment] 2024-02-22 18:48
Everything looks good to me button rpesses working, temps loading, fans loading.  Also you can now say this works on idrac 7 as well lol.

![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/46956acc-a562-4c45-bffb-c333d262adad)

**Comment by Breina** [comment] 2024-02-22 18:49
Awesome! Thanks for testing! :)

**Comment by taylor-mcdonald** [comment] 2024-04-01 14:43
I know this is marked as closed, but I'm having a similar problem when adding my second R720.  Both are iDrac 7 enterprise.  Even though it looks like  two devices in the picture, there is only one device and the entities get all mixed up.  Any ideas on how to fix?

![image](https://github.com/Breina/idrac_power_monitor/assets/98405714/398d6bb3-4a3b-4484-866c-3f5570d7857c)

**Comment by smitch35** [comment] 2024-04-01 14:47
First thing I think is make sure your on the latest version. Also I had to rename entites as I added devices to keep them traight.

**Comment by taylor-mcdonald** [comment] 2024-04-01 14:57
I am on version 1.2.2 and did rename entities of the first 720 before adding the second.  All the entities for the second still get lumped under the first device.

Does this part show more than one device for you?
![image](https://github.com/Breina/idrac_power_monitor/assets/98405714/a9cb7d99-7c35-475f-84b5-a25fbed2fd0c)

**Comment by smitch35** [comment] 2024-04-01 15:03
![image](https://github.com/Breina/idrac_power_monitor/assets/4818151/b82dd920-a271-4ff1-a3e2-a5c4e68da9ab)

**Comment by cbrherms** [comment] 2024-04-17 01:45
I have run in to the same issue also with 3 separate machines of various models on v1.2.2 with HA 2024.4.3.
Appears all entities are associated with the final server added.

**Comment by Breina** [comment] 2024-04-17 18:40
Can you guys please check the device serial is filled in properly?

![image](https://github.com/Breina/idrac_power_monitor/assets/3009914/c4b0798a-a10a-4bf0-a53e-762b1b867dd1)

If it's not, that means that entities from a previous version persisted. This is because the unique ID had been updated, which I try to avoid as much as possible.

Please try this procedure;
1. Remove the integration
2. Restart
3. Remove all the old entities that are now no longer provided by the integration
4. Restart
5. Re-add the integration

**Comment by taylor-mcdonald** [comment] 2024-04-17 21:57
I confirmed that the serial number pulled during the integration setup, matches the initial server I added.  Although, the only place I can see that serial number listed anywhere is by going to https://host/redfish/v1/Chassis/System.Embedded.1.

I followed the listed procedure and ended up back with the same result (the number of entities are different, but there is only one overall device even though two are shown)
![image](https://github.com/Breina/idrac_power_monitor/assets/98405714/01310ac9-343c-458c-87cf-494fdd897969)

**Comment by cbrherms** [comment] 2024-04-18 00:59
Have also followed the procedure steps and got the same results as before. One device created with all entities associated with it. 3 separate config entries though, with entities assigned to he correct config entry, but all assigned to the same device. And, the main device is updated to show the serial number, name, etc, of a new device when added.

Same device page as each device is added (notice serial and name alsonchange):

![Screenshot_20240418-011225~3](https://github.com/Breina/idrac_power_monitor/assets/12373955/fbf5188b-e7dc-491d-8f15-b24777bbb28a)
![Screenshot_20240418-011453~3](https://github.com/Breina/idrac_power_monitor/assets/12373955/4fcadaa5-07cd-41f6-863f-f4431e4f4792)
![Screenshot_20240418-011616~3](https://github.com/Breina/idrac_power_monitor/assets/12373955/a4d36812-2aab-4a72-8d38-f96e8af30696)
![Screenshot_20240418-014253](https://github.com/Breina/idrac_power_monitor/assets/12373955/3b21a590-3872-412d-b9d7-c32e4d0836e1)

On that "Devices" block on the integration page, hovering over the "1 device" link in each entry I can see they each have the same URL, so look to all be pointing to the same device.

Just having a quick look at the config flow, but it looks like there's no process to set a unique ID to the device when added, like setting it to the serial number? I'm assuming that's related to it all being associated to the same device with different configs, rather than a new device entirely? (I'm not all too familiar with how the flow works these days)
[https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#unique-ids](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#unique-ids)

**Comment by Breina** [comment] 2024-04-29 20:34
Alright lads, I managed to reproduce it through mocking and fixed the issue in v1.2.3.

Please report back. :)

**Comment by cbrherms** [comment] 2024-04-30 01:14
> Alright lads, I managed to reproduce it through mocking and fixed the issue in v1.2.3.
> 
> Please report back. :)

Yup, can confirm creating separate devices now.

Did play around with it a bit over the weekend and came to the same conclusion that it was because of the identifiers added to the device on creation/update, specifically because each one had  `('domain', DOMAIN)`  added as an identifier tuple

Though, I don't think the tuple really works as a 2 part label:value kind of pairing where the first part is describing what the value is, so should probably instead be set by `identifiers={(DOMAIN, serial)},` so that the integration's domain is added as an identifier of what created it in the same way that other integrations do. 

Also, two of the entities are created with identical unique id's, will pop a wee PR with these two changes.

**Comment by taylor-mcdonald** [comment] 2024-05-02 11:27
Thanks for the fix.  I now have 2 devices.  Were the fans part of the entities that were grabbed before?  I don't see them now.  Also, using the Power On control gives this pop-up, but the servers turn on fine.

![image](https://github.com/Breina/idrac_power_monitor/assets/98405714/ae149617-a675-4a4d-9ca8-0f552223ee9d)

**Comment by Breina** [comment] 2024-05-02 22:03
@taylor-mcdonald Please upgrade to v1.2.6 and put some logs in here, I'll have a look.

**Closed** 2024-06-02 11:29 UTC
